###PRODUCT CONTROLLERS
###Add new product
POST http://localhost:4503/product
Content-Type: application/json

{
     "productName": "LG V50 ThinQ",
   "productDescription": "LG V50 ThinQ",
   "price": 25990,
   "productImage": "https://ke.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/69/315184/1.jpg?2778",
   "stock": 49
}


###Get all products
GET http://localhost:4503/product/all
Content-Type: application/json

###Get one product
GET http://localhost:4503/product/one/3c986216-b547-4162-8daf-92188a800c42


###Update product
PUT http://localhost:4503/product/3c986216-b547-4162-8daf-92188a800c42
Content-Type: application/json


{
   "productName": "Oraimo Headsets",
   "productDescription": "Rock Stereo Bass Super Long Playtime IPX5 Waterproof",
   "price": 2200,
   "productImage": "https://ke.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/71/486778/1.jpg?8858",
   "stock": 454
}

###Delete product
DELETE http://localhost:4503/product/3c986216-b547-4162-8daf-92188a800c42



### MANAGE CART

###add to cart
POST http://localhost:4503/cart/d7abc609-b651-404d-81a1-8d6bf5c1855c
Content-Type: application/json

{
   "productId": "229a1597-b2d5-46c7-a37b-2c58a424faab",
   "orderNo": 2
}


###user view all products in cart
GET  http://localhost:4503/cart/view/d7abc609-b651-404d-81a1-8d6bf5c1855c

###user remove item from cart
DELETE http://localhost:4503/cart/722e4d88-b2e8-4cc3-b8c8-6b1ad7433bd1
Content-Type: application/json

###
DELETE http://localhost:4503/cart/3652a832-dfb0-4019-ac2a-c8060112826e






###USERS CONTROLLERS

### Register user
POST http://localhost:4503/users/register
Content-Type: application/json

{
   "UserName": "User Kevin",
   "Email": "kevinmathenge17@gmail.com",
   "Password": "12345678",
   "PhoneNumber": "254726023495",
   "isActive": 1,
   "isAdmin": 1


}
### get user details
GET http://localhost:4503/users/f3b4ebe7-f121-4b67-a58d-1f1c8f900f59

### Login user
POST http://localhost:4503/users/login
Content-Type: application/json

{
 "Email": "calyndemo16@gmail.com",
 "Password": "12345678"


}

### Get all customers
GET http://localhost:4503/users/customers/get-all-customers


### Update user
PATCH http://localhost:4503/users/update-information/f3b4ebe7-f121-4b67-a58d-1f1c8f900f59
Content-Type: application/json

{
    "Email": "Kevin.mathenge@mail.com",
    "PhoneNumber": "123456789"
}


### Rset passsword
POST http://localhost:4503/users/password-reset-request
Content-Type: application/json

{
   "Email": "kev@mail.com"
}

### Deactivate account

POST http://localhost:4503/users/disable-account/172823eb-4088-4c1c-961e-62ce515bf8f9
# EXEC UpdateUserProcedure
#     @UserID = 'f3b4ebe7-f121-4b67-a58d-1f1c8f900f59',
#     @Email = 'Kevin.mathenge@mail.com',
#     @PhoneNumber = '1234567890';