###PRODUCT CONTROLLERS
###Add new product
POST http://localhost:4503/product
Content-Type: application/json

{
    "productName": "five pac",
    "productDescription": "five pac",
    "price": 500000000,
    "productImage": "https://www.pac.com",
    "stock": 9
}


###Get all products
GET http://localhost:4503/product/all
Content-Type: application/json

###Get one product
GET http://localhost:4503/product/one/5efdf8d9-301f-418c-9bec-7560b853c28e


###Update product
PUT http://localhost:4503/product/5efdf8d9-301f-418c-9bec-7560b853c28e
Content-Type: application/json


{
    "productName": "Steel door",
    "productDescription": "To prevent thieves",
    "price": 400000000,
    "productImage": "https://www.door.com",
    "stock": 4543
}

###Delete product
DELETE http://localhost:4503/product/5efdf8d9-301f-418c-9bec-7560b853c28e



### MANAGE CART

###add to cart
POST http://localhost:4503/cart/48886de7-3ef7-4bbc-ad2c-8d01298340ea
Content-Type: application/json

{
    "productId": "c5db4628-6096-4b2e-a50f-1691d33e25be"
}


###user view all products in cart
GET  http://localhost:4503/cart/view/48886de7-3ef7-4bbc-ad2c-8d01298340ea 

###user remove item from cart
DELETE http://localhost:4503/cart/ffa9341a-a42f-4ef5-9d9b-32dfc7c30ddb
Content-Type: application/json








###USERS CONTROLLERS

### Register user
POST http://localhost:4503/users/register
Content-Type: application/json

{
    "UserName": "Selly Wainaina",
    "Email": "selester@gmail.com",
    "Password": "12345678",
    "PhoneNumber": "254722000005",
    "isAdmin": 0


}
### get user details
GET http://localhost:4503/users/6e358199-6653-4351-9d27-1136d398aa48

### Login user
POST http://localhost:4503/users/login
Content-Type: application/json

{
  "Email": "selesterat@gmail.com",
  "Password": "12345678"


}

### Get all customers
GET http://localhost:4503/users/customers/get-all-customers

