###PRODUCT CONTROLLERS
###Add new product
POST http://localhost:4503/product
Content-Type: application/json

{
   "productName": "Classic Business Quartz Wrist Watch",
   "productDescription": "Fashion Mens Casual Classic Business Quartz Calendar Wrist Watches Men",
   "price": 95499,
   "productImage": "https://ke.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/59/0416001/1.jpg?1735",
   "stock": 65
}


###Get all products
GET http://localhost:4503/product/all
Content-Type: application/json

###Get one product
GET http://localhost:4503/product/one/c5db4628-6096-4b2e-a50f-1691d33e25be


###Update product
PUT http://localhost:4503/product/60a15ccc-9eda-4720-a0c3-16ff9d0fd9e8
Content-Type: application/json


{
   "productName": "Steel door",
   "productDescription": "To prevent thieves",
   "price": 400000000,
   "productImage": "https://images.pexels.com/photos/7054511/pexels-photo-7054511.jpeg?auto=compress&cs=tinysrgb&w=600",
   "stock": 4543
}

###Delete product
DELETE http://localhost:4503/product/c5db4628-6096-4b2e-a50f-1691d33e25be



### MANAGE CART

###add to cart
POST http://localhost:4503/cart/8caf46b1-080b-4e46-b7d2-57780ea5684f
Content-Type: application/json

{
   "productId": "090a3e89-3dcb-4f87-a0e1-10c28849a49a",
   "orderNo": 2
}


###user view all products in cart
GET  http://localhost:4503/cart/view/f9addcd4-4aa9-4f7b-9e42-b4696e8d22a1

###user remove item from cart
DELETE http://localhost:4503/cart/722e4d88-b2e8-4cc3-b8c8-6b1ad7433bd1
Content-Type: application/json








###USERS CONTROLLERS

### Register user
POST http://localhost:4503/users/register
Content-Type: application/json

{
   "UserName": "Calvince Ndemo",
   "Email": "calyndemo17@gmail.com",
   "Password": "12345678",
   "PhoneNumber": "254722080405",
   "isAdmin": 0


}
### get user details
GET http://localhost:4503/users/6e358199-6653-4351-9d27-1136d398aa48

### Login user
POST http://localhost:4503/users/login
Content-Type: application/json

{
 "Email": "calyndemo16@gmail.com",
 "Password": "12345678"


}

### Get all customers
GET http://localhost:4503/users/customers/get-all-customers


### Update user
PATCH http://localhost:4503/users/update-information/e3e64beb-fl;ef8-42dbadc4-cccaa4c5ac82
Content-Type: application/json

{
    "Email": "Kevin.mathenge@mail.com"
}
